modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/LoTek2012/AstraCraft/issues/new"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/LoTek2012/AstraCraft/refs/heads/main/updates.json"
displayURL="https://github.com/LoTek2012/AstraCraft"
authors="Loan"
description='''
An advanced minecraft space exploration mod powered by a fully customizable procedural planetary and solar system generation engine
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="astralib"
    type="required"
    versionRange="[1.0.0]"
    ordering="AFTER"
    side="BOTH"
